<wsdl:definitions name="EDMPlatformService" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:i0="http://www.elliemae.com/encompass/platform" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tempuri.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
	<wsdl:import namespace="http://www.elliemae.com/encompass/platform" location="WSDL_1887184314.wsdl"/>
	<wsdl:types/>
	<wsdl:binding name="BasicHttpBinding_EDMPlatformService" type="i0:EDMPlatformService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="AttachmentGet">
			<soap:operation soapAction="http://www.elliemae.com/encompass/platform/EDMPlatformService/AttachmentGet" style="document"/>
			<wsdl:input name="AttachmentGetRequest">
				<soap:header message="i0:AttachmentGetRequest_Headers" part="SecurityContext" use="literal"/>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="AttachmentGetResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="DocumentLogListGet">
			<soap:operation soapAction="http://www.elliemae.com/encompass/platform/EDMPlatformService/DocumentLogListGet" style="document"/>
			<wsdl:input name="DocumentLogListGetRequest">
				<soap:header message="i0:DocumentLogListGetRequest_Headers" part="SecurityContext" use="literal"/>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="DocumentLogListGetResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="AttachmentCreate">
			<soap:operation soapAction="http://www.elliemae.com/encompass/platform/EDMPlatformService/AttachmentCreate" style="document"/>
			<wsdl:input name="AttachmentSaveRequest">
				<soap:header message="i0:AttachmentSaveRequest_Headers" part="SecurityContext" use="literal"/>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="AttachmentSaveResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="SupportingDataGet">
			<soap:operation soapAction="http://www.elliemae.com/encompass/platform/EDMPlatformService/SupportingDataGet" style="document"/>
			<wsdl:input name="SupportingDataGetRequest">
				<soap:header message="i0:SupportingDataGetRequest_Headers" part="SecurityContext" use="literal"/>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="SupportingDataGetResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="SupportingDataSave">
			<soap:operation soapAction="http://www.elliemae.com/encompass/platform/EDMPlatformService/SupportingDataSave" style="document"/>
			<wsdl:input name="SupportingDataSaveRequest">
				<soap:header message="i0:SupportingDataSaveRequest_Headers" part="SecurityContext" use="literal"/>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="EDMPlatformService">
		<wsdl:port name="BasicHttpBinding_EDMPlatformService" binding="tns:BasicHttpBinding_EDMPlatformService">
			<soap:address location="http://ed1vwbenc3009.dco.elmae/EDMPlatform/EDMPlatformService.svc"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>